const $ = s => document.querySelector(s);
const fileInput = $('#fileInput'), dropzone = $('#dropzone'), chooseBtn = $('#chooseBtn'), resizeBtn = $('#resizeBtn'), clearBtn = $('#clearBtn');
const countValue = $('#countValue'), inputSizeValue = $('#inputSizeValue'), modeValue = $('#modeValue'), progressBar = $('#progressBar'), progressText = $('#progressText'), progressLabel = $('#progressLabel'), statusText = $('#statusText'), fileTable = $('#fileTable'), previewGrid = $('#previewGrid');
const widthInput = $('#width'), heightInput = $('#height'), modeInput = $('#mode'), formatInput = $('#format'), qualityInput = $('#quality'), zipNameInput = $('#zipName');
let files = [], working = false;
chooseBtn.onclick = ()=>fileInput.click(); dropzone.onclick = ()=>fileInput.click(); fileInput.onchange = e => setFiles([...e.target.files]); clearBtn.onclick = ()=>{ if(working) return; setFiles([]); fileInput.value=''; }; resizeBtn.onclick = run; modeInput.onchange = ()=> modeValue.textContent = modeInput.value === 'fit' ? 'Fit' : 'Exact';
['dragover','dragenter'].forEach(evt => dropzone.addEventListener(evt, e => { e.preventDefault(); dropzone.classList.add('dragover'); })); ['dragleave','drop'].forEach(evt => dropzone.addEventListener(evt, e => { e.preventDefault(); if(evt==='drop') setFiles([...e.dataTransfer.files].filter(f=>f.type.startsWith('image/'))); dropzone.classList.remove('dragover'); }));
function setFiles(next){ files = next.filter(f => ['image/jpeg','image/png','image/webp'].includes(f.type)); countValue.textContent=files.length; inputSizeValue.textContent=PDS.bytes(files.reduce((a,b)=>a+b.size,0)); resizeBtn.disabled=!files.length; clearBtn.disabled=!files.length; progressBar.style.width='0%'; progressText.textContent='0%'; progressLabel.textContent=files.length?'Готово к обработке':'Ожидание'; statusText.textContent=files.length?`Загружено файлов: ${files.length}`:'Файлы не выбраны.'; renderRows(); previewGrid.innerHTML = files.slice(0,6).map(f=>`<div class="preview-card"><img src="${URL.createObjectURL(f)}"><div class="title">${PDS.escape(f.name)}</div><div class="meta">${PDS.bytes(f.size)}</div></div>`).join(''); }
function renderRows(rows){ const data = rows || files.map(f => ({name:f.name,inSize:f.size,outSize:null,status:'Ожидание',error:false})); fileTable.innerHTML = `<div class="table-head"><div>Файл</div><div>Исходный</div><div>После</div><div>Статус</div></div>` + (data.length ? data.map(r => `<div class="table-row"><div class="name-ellipsis">${PDS.escape(r.name)}</div><div>${PDS.bytes(r.inSize)}</div><div>${r.outSize?PDS.bytes(r.outSize):'—'}</div><div class="${r.error?'err':'ok'}">${r.status}</div></div>`).join('') : `<div class="table-row"><div>Пока нет файлов</div><div>—</div><div>—</div><div>—</div></div>`); }
async function processFile(file, opts){ const img = await PDS.loadImage(file); let w = opts.width, h = opts.height; if(opts.mode === 'fit'){ const s = PDS.fitSize(img.naturalWidth||img.width, img.naturalHeight||img.height, opts.width, opts.height, false); w = s.width; h = s.height; } const canvas = document.createElement('canvas'); canvas.width = w; canvas.height = h; canvas.getContext('2d',{alpha:true}).drawImage(img,0,0,w,h); return await PDS.canvasToBlob(canvas, opts.format, opts.format === 'image/png' ? undefined : opts.quality); }
async function run(){ if(working || !files.length) return; working=true; resizeBtn.disabled=true; clearBtn.disabled=true; const opts = { width:PDS.clamp(parseInt(widthInput.value,10)||1200,1,5000), height:PDS.clamp(parseInt(heightInput.value,10)||1200,1,5000), mode:modeInput.value, format:formatInput.value, quality:PDS.clamp(parseInt(qualityInput.value,10)||82,1,100)/100 }; const ext=PDS.extByMime(opts.format), zipName=PDS.sanitize(zipNameInput.value.trim()||'resized-images'); const zip=new JSZip(); const rows=[]; progressLabel.textContent='Изменение размера'; for(let i=0;i<files.length;i++){ const file=files[i]; statusText.textContent=`Обработка ${i+1} из ${files.length}: ${file.name}`; try{ const blob=await processFile(file, opts); zip.file(`${PDS.sanitize(PDS.baseName(file.name))}.${ext}`, blob); rows.push({name:file.name,inSize:file.size,outSize:blob.size,status:'Готово',error:false}); }catch(e){ rows.push({name:file.name,inSize:file.size,outSize:null,status:'Ошибка',error:true}); } renderRows(rows); const pct=Math.round(((i+1)/files.length)*100); progressBar.style.width=`${pct}%`; progressText.textContent=`${pct}%`; } try{ progressLabel.textContent='Формирование ZIP'; const blob=await zip.generateAsync({type:'blob'}, meta=>{ const pct=Math.round(meta.percent); progressBar.style.width=`${pct}%`; progressText.textContent=`${pct}%`; }); PDS.downloadBlob(blob, `${zipName}.zip`); progressLabel.textContent='Готово'; statusText.textContent=`Архив ${zipName}.zip скачан.`; } finally { working=false; resizeBtn.disabled=false; clearBtn.disabled=false; } }
renderRows();
