const $ = s => document.querySelector(s);
const hexInput = $('#hexInput'), rgbInput = $('#rgbInput'), hslInput = $('#hslInput'), swatch = $('#swatch'), paletteGrid = $('#paletteGrid'), statusText = $('#statusText');
$('#fromHexBtn').onclick = () => { try { applyFromHex(hexInput.value); } catch(e){ statusText.textContent = `Ошибка: ${e.message}`; } };
$('#fromRgbBtn').onclick = () => { try { applyFromRgb(rgbInput.value); } catch(e){ statusText.textContent = `Ошибка: ${e.message}`; } };
$('#fromHslBtn').onclick = () => { try { applyFromHsl(hslInput.value); } catch(e){ statusText.textContent = `Ошибка: ${e.message}`; } };
function normalizeHex(hex){ let h = String(hex).trim().replace('#',''); if(h.length===3) h = h.split('').map(c=>c+c).join(''); if(!/^[0-9a-fA-F]{6}$/.test(h)) throw new Error('HEX должен быть в формате #RRGGBB или #RGB'); return '#' + h.toLowerCase(); }
function hexToRgb(hex){ const h = normalizeHex(hex).slice(1); return { r: parseInt(h.slice(0,2),16), g: parseInt(h.slice(2,4),16), b: parseInt(h.slice(4,6),16) }; }
function rgbToHex(r,g,b){ return '#' + [r,g,b].map(v => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2,'0')).join(''); }
function rgbToHsl(r,g,b){ r/=255; g/=255; b/=255; const max=Math.max(r,g,b), min=Math.min(r,g,b); let h,s,l=(max+min)/2; if(max===min){ h=s=0; } else { const d=max-min; s = l>0.5 ? d/(2-max-min) : d/(max+min); switch(max){ case r: h=(g-b)/d + (g<b?6:0); break; case g: h=(b-r)/d + 2; break; default: h=(r-g)/d + 4; } h/=6; } return { h: Math.round(h*360), s: Math.round(s*100), l: Math.round(l*100) }; }
function hslToRgb(h,s,l){ h=((h%360)+360)%360/360; s/=100; l/=100; if(s===0){ const v=Math.round(l*255); return {r:v,g:v,b:v}; } const hue2rgb=(p,q,t)=>{ if(t<0)t+=1; if(t>1)t-=1; if(t<1/6)return p+(q-p)*6*t; if(t<1/2)return q; if(t<2/3)return p+(q-p)*(2/3-t)*6; return p; }; const q=l<0.5?l*(1+s):l+s-l*s; const p=2*l-q; return { r: Math.round(hue2rgb(p,q,h+1/3)*255), g: Math.round(hue2rgb(p,q,h)*255), b: Math.round(hue2rgb(p,q,h-1/3)*255) }; }
function parseRgb(str){ const parts=String(str).split(',').map(s=>parseFloat(s.trim())); if(parts.length!==3 || parts.some(v=>Number.isNaN(v))) throw new Error('RGB должен быть в виде 255, 255, 255'); return { r: parts[0], g: parts[1], b: parts[2] }; }
function parseHsl(str){ const parts=String(str).replace(/%/g,'').split(',').map(s=>parseFloat(s.trim())); if(parts.length!==3 || parts.some(v=>Number.isNaN(v))) throw new Error('HSL должен быть в виде 0, 0%, 100%'); return { h: parts[0], s: parts[1], l: parts[2] }; }
function update(rgb){ const hex = rgbToHex(rgb.r,rgb.g,rgb.b); const hsl = rgbToHsl(rgb.r,rgb.g,rgb.b); hexInput.value = hex; rgbInput.value = `${rgb.r}, ${rgb.g}, ${rgb.b}`; hslInput.value = `${hsl.h}, ${hsl.s}%, ${hsl.l}%`; swatch.style.background = hex; statusText.textContent = 'Значения обновлены.'; renderPalette(hsl); }
function applyFromHex(v){ update(hexToRgb(v)); }
function applyFromRgb(v){ update(parseRgb(v)); }
function applyFromHsl(v){ update(hslToRgb(...Object.values(parseHsl(v)))); }
function renderPalette(base){ const steps=[-30,-20,-10,0,10,20,30,40,50]; paletteGrid.innerHTML = steps.map(step=>{ const l=Math.max(0,Math.min(100,base.l+step)); const rgb=hslToRgb(base.h,base.s,l); const hex=rgbToHex(rgb.r,rgb.g,rgb.b); return `<div class="preview-card"><div style="height:120px;border-radius:14px;border:1px solid var(--line-soft);background:${hex}"></div><div class="title">${hex}</div><div class="meta">L ${l}%</div><button class="btn btn-dark copy-btn" data-copy="${hex}">Копировать</button></div>`; }).join(''); document.querySelectorAll('[data-copy]').forEach(btn => btn.onclick = async () => { await navigator.clipboard.writeText(btn.dataset.copy); statusText.textContent = `Скопировано: ${btn.dataset.copy}`; }); }
applyFromHex('#ffffff');
